// Frontend Development/handson5/task1/src/components/CourseCard.jsx
function CourseCard(props) {
  return (
    <div className="course-card">
      <h2>{props.name}</h2>

      <p><strong>Code:</strong> {props.code}</p>

      <p><strong>Credits:</strong> {props.credits}</p>

      <p><strong>Grade:</strong> {props.grade}</p>
    </div>
  );
}

export default CourseCard;

// Frontend Development/handson8/Task1/src/components/CourseCard.vue
<template>
  <div class="card">
    <h3>{{ name }}</h3>
    <p>Code : {{ code }}</p>
    <p>Credits : {{ credits }}</p>
    <p>Grade : {{ grade }}</p>
  </div>
</template>

<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String
})
</script>

<style scoped>
.card{
  border:1px solid #ccc;
  border-radius:8px;
  padding:15px;
  margin:10px;
}
</style>
