// Frontend Development/handson8/Task3/src/components/Header.vue
<template>
  <header style="background:#1976d2; color:white; padding:15px;">
    <h2>Student Portal</h2>

    <p>
      Enrolled Courses:
      {{ store.enrolledCourses.length }}
    </p>
  </header>
</template>

<script setup>
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

// Frontend Development/handson6/Task3/src/components/Header.jsx
import { useSelector } from "react-redux";

function Header() {

  const enrolledCourses = useSelector(
    (state) => state.enrollment.enrolledCourses
  );

  return (
    <header>
      <h1>Student Portal</h1>

      <h3>Enrolled: {enrolledCourses.length}</h3>
    </header>
  );
}

export default Header;
